/**
 * Button Schema — builder-agnostic property schema for the Button component.
 * The Puck adapter later maps these fields into its configuration.
 */

import type { ComponentSchema } from "../../../src/contracts/ComponentSchema";
import { ButtonVariant, ButtonSize, ButtonShape } from "./variants";

export const buttonSchema: ComponentSchema = {
  componentId: "klin-button",
  fields: [
    {
      key: "text",
      label: "Text",
      type: "string",
      defaultValue: "Button",
      required: true,
      group: "Content",
      order: 1,
      description: "The visible text inside the button",
    },
    {
      key: "variant",
      label: "Variant",
      type: "select",
      defaultValue: "primary",
      required: true,
      group: "Appearance",
      order: 2,
      description: "Visual style variant",
      options: Object.entries(ButtonVariant).map(([label, value]) => ({ label, value })),
    },
    {
      key: "size",
      label: "Size",
      type: "select",
      defaultValue: "md",
      required: true,
      group: "Appearance",
      order: 3,
      description: "Button size preset",
      options: Object.entries(ButtonSize).map(([label, value]) => ({ label, value })),
    },
    {
      key: "shape",
      label: "Shape",
      type: "select",
      defaultValue: "rounded",
      required: true,
      group: "Appearance",
      order: 4,
      description: "Border shape preset",
      options: Object.entries(ButtonShape).map(([label, value]) => ({ label, value })),
    },
    {
      key: "icon",
      label: "Icon",
      type: "icon",
      defaultValue: "",
      required: false,
      group: "Content",
      order: 5,
      description: "Optional icon identifier",
    },
    {
      key: "iconPosition",
      label: "Icon Position",
      type: "select",
      defaultValue: "left",
      required: false,
      group: "Content",
      order: 6,
      options: [
        { label: "Left", value: "left" },
        { label: "Right", value: "right" },
      ],
    },
    {
      key: "loading",
      label: "Loading",
      type: "boolean",
      defaultValue: false,
      required: false,
      group: "State",
      order: 7,
    },
    {
      key: "disabled",
      label: "Disabled",
      type: "boolean",
      defaultValue: false,
      required: false,
      group: "State",
      order: 8,
    },
    {
      key: "fullWidth",
      label: "Full Width",
      type: "boolean",
      defaultValue: false,
      required: false,
      group: "Layout",
      order: 9,
    },
    {
      key: "linkUrl",
      label: "Link URL",
      type: "url",
      defaultValue: "",
      required: false,
      group: "Actions",
      order: 10,
      description: "Renders the button as a link when provided",
    },
    {
      key: "target",
      label: "Link Target",
      type: "select",
      defaultValue: "_self",
      required: false,
      group: "Actions",
      order: 11,
      options: [
        { label: "Same Window", value: "_self" },
        { label: "New Tab", value: "_blank" },
      ],
    },
    {
      key: "animation",
      label: "Animation",
      type: "select",
      defaultValue: "scale",
      required: false,
      group: "Effects",
      order: 12,
      description: "Micro-animation preset",
      options: [
        { label: "None", value: "none" },
        { label: "Fade", value: "fade" },
        { label: "Scale", value: "scale" },
        { label: "Bounce", value: "bounce" },
        { label: "Ripple", value: "ripple" },
        { label: "Pulse", value: "pulse" },
      ],
    },
    {
      key: "ariaLabel",
      label: "ARIA Label",
      type: "string",
      defaultValue: "",
      required: false,
      group: "Accessibility",
      order: 13,
      description: "Accessible label override for screen readers",
    },
  ],
};
