export const ERROR_CODES = {
  CONFIGURATION: "ERR_CONFIGURATION",
  REGISTRY: "ERR_REGISTRY",
  RENDERER: "ERR_RENDERER",
  BUILDER: "ERR_BUILDER",
  VALIDATION: "ERR_VALIDATION",
  UNKNOWN: "ERR_UNKNOWN",
} as const;
